
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.253:3306/zcrm?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ZCRM
    password: xEys6RbKMiZeTinT
  http:
    multipart:
      enabled: false

  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-request-size: 10MB #最大请求文件的大小
      max-file-size: 10MB #设置单个文件最大长度
      file-size-threshold: 100MB #当文件达到多少时进行磁盘写入



mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true       # user_code   ==> userCode


server:
  port: 8188

mapper:
  mappers: com.util.mapper.BaseMapper
  identity: MYSQL


pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
